/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Rating = IDL.Record({
  'id' : IDL.Nat,
  'stars' : IDL.Nat,
  'timestamp' : Time,
  'reviewer' : IDL.Principal,
});
export const Review = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'timestamp' : Time,
  'reviewer' : IDL.Principal,
});

export const idlService = IDL.Service({
  'getAllRatings' : IDL.Func([], [IDL.Vec(Rating)], ['query']),
  'getAllReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'submitRating' : IDL.Func([IDL.Nat], [], []),
  'submitReview' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Rating = IDL.Record({
    'id' : IDL.Nat,
    'stars' : IDL.Nat,
    'timestamp' : Time,
    'reviewer' : IDL.Principal,
  });
  const Review = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'timestamp' : Time,
    'reviewer' : IDL.Principal,
  });
  
  return IDL.Service({
    'getAllRatings' : IDL.Func([], [IDL.Vec(Rating)], ['query']),
    'getAllReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'submitRating' : IDL.Func([IDL.Nat], [], []),
    'submitReview' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };